"""initial tables

Revision ID: dcad2b764ffd
Revises: 
Create Date: 2026-02-28 16:45:11.173050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcad2b764ffd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('mcp_server', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('test_case_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    op.drop_table('eval_results')
    op.drop_table('audit_logs')
    op.drop_table('agent_decisions')
    # ### end Alembic commands ###
